apiVersion: apps/v1
kind: Deployment
metadata:
  name: deployment-2048-{{ .Values.env }}
  namespace: {{ .Values.namespace }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app.kubernetes.io/name: app-2048-{{ .Values.env }}
  template:
    metadata:
      labels:
        app.kubernetes.io/name: app-2048-{{ .Values.env }}
    spec:
      containers:
        - name: app-2048
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - containerPort: 80
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
