apiVersion: v1
kind: Service
metadata:
  name: service-2048-{{ .Values.env }}
  namespace: {{ .Values.namespace }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: 80
      protocol: TCP
  selector:
    app.kubernetes.io/name: app-2048-{{ .Values.env }}
