apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: game-2048-prod
  namespace: argocd
spec:
  project: default
  source:
    repoURL: git@github.com:valerig-yaar/ArgoCD-apps.git
    targetRevision: HEAD
    path: charts/game-2048
    helm:
      valueFiles:
        - ../game-2048-prod/values.yaml
  destination:
    server: https://kubernetes.default.svc
    namespace: prod
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true