apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: simpleWeb-dev
  namespace: argocd
spec:
  project: default
  source:
    repoURL: git@github.com:valerig-yaar/ArgoCD-apps.git
    targetRevision: HEAD
    path: charts/simpleWeb
    helm:
      valueFiles:
        - ../simpleWeb-dev/values.yaml
  destination:
    server: https://kubernetes.default.svc
    namespace: dev
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true